# Generated by Django 4.2.4 on 2023-08-11 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity', '0002_alter_reqlist_helpers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqlist',
            name='helpers',
            field=models.ManyToManyField(blank=True, related_name='helpers', to=settings.AUTH_USER_MODEL),
        ),
    ]
